---
# ═══════════════════════════════════════════════════════════════════════════
# Antigravity Infrastructure - Master Playbook
# ═══════════════════════════════════════════════════════════════════════════
# Step 0-1: Ansible User Bootstrap (최초 1회 실행)
# 설명: 모든 서버에 'ansible' 계정을 생성하고 SSH 키를 배포합니다.
# 주의: 이 단계는 Root 계정으로 실행해야 하므로, 아래와 같이 별도로 실행하거나 주석 해제 후 -u root 옵션 필요
# - import_playbook: playbooks/00_bootstrap_ansible_user.yml

# Step 0: 네트워크 프로비저닝 (SSH 키 배포 및 IP/DNS 설정)
# - SSH Key 배포 (localhost)
# - 정적 IP 할당 및 네트워크 인터페이스 설정 (nmcli)
# - import_playbook: playbooks/00_network_provisioning.yml

# Step 1: 모든 서버 기초 환경 구축
# - OS 기본 설정 (NTP, 방화벽, 패키지 등)
- import_playbook: playbooks/01_common_setup.yml

# Step 1.5: 보안 계층 (Security Tier) 구축
# - SECURE(GW), WAF, DNS 서버 설정
- import_playbook: playbooks/08_deploy_security.yml

# Step 2: PC4 데이터베이스 및 스토리지 구축 (Kubernetes 외부 인프라)
# - MySQL Replication (Master/Slave/Backup)
# - ProxySQL (DB 로드밸런싱)
# - Etcd Cluster (Key-Value Store)
# - NFS Storage 서버 구성
- import_playbook: playbooks/04_deploy_db.yml

# Step 3: PC2, PC3, PC6 쿠버네티스 클러스터 구축 (초기화 후 설치)
# - 3-1: 기존 노드 초기화 (Reset) -> 찌꺼기 제거 및 클린 상태 확보
- import_playbook: playbooks/02-1_reset_k8s_node.yml
# - 3-2: 클러스터 구축 (Install) -> Master(PC2) + Worker(PC3, PC6) + CNI(Flannel)
- import_playbook: playbooks/02_k8s_install.yml

# Step 4: 모니터링 시스템 배포 (PC5)
# - Prometheus(수집), Grafana(시각화), Alertmanager(알림)
# - Node Exporter: 모든 노드에 설치되어 시스템 지표 수집
- import_playbook: playbooks/03_deploy_monitoring.yml

# Step 5: CI/CD 시스템 배포 (PC5)
# - Jenkins: 빌드 및 배포 파이프라인 실행
# - Gitea: 내부 Git 리포지토리 (소스코드 관리)
- import_playbook: playbooks/05_deploy_cicd.yml

# Step 6: Docker Registry 배포 (PC5)
# - Harbor: 프라이빗 Docker 이미지 저장소
# - Docker Hub 미러링 및 보안 스캔 기능 포함
- import_playbook: playbooks/06_deploy_registry.yml

# Step 7: ArgoCD 배포 (GitOps CD)
# - ArgoCD: Kubernetes 상태를 Git과 동기화 (GitOps 구현)
# - NodePort를 통해 외부 접속 가능
- import_playbook: playbooks/07_deploy_argocd.yml
# - ArgoCD Applications 설정 (App of Apps 패턴)
# - 개별 마이크로서비스(map, energy, kma, my-web)를 자동으로 등록
- import_playbook: playbooks/07_deploy_argocd_apps.yml

