# ═══════════════════════════════════════════════════════════════════════════
# Playbook 03: Label Kubernetes Nodes - 노드 역할 라벨링
# ═══════════════════════════════════════════════════════════════════════════
- name: Apply Node Labels
  hosts: K8S_Primary_Master
  become: yes
  tasks:
    - name: Label Worker Node 1 (Weather)
      command: kubectl label nodes k8s-workernode1 role=weather --overwrite

    - name: Label Worker Node 2 (Energy)
      command: kubectl label nodes k8s-workernode2 role=energy --overwrite

    - name: Label Worker Node 3 (Map - Reserved)
      command: kubectl label nodes k8s-workernode3 role=map --overwrite

    - name: Label Worker Node 4 (Web)
      command: kubectl label nodes k8s-workernode4 role=web --overwrite

    - name: Label Worker Node 5 (Gateway - Reserved)
      command: kubectl label nodes k8s-workernode5 role=gateway --overwrite

    - name: Label Worker Node 6 (OAuth - Reserved)
      command: kubectl label nodes k8s-workernode6 role=oauth --overwrite
      
    - name: Verify Labels
      command: kubectl get nodes --show-labels
      register: label_result

    - debug:
        msg: "{{ label_result.stdout_lines }}"
