---
# ═══════════════════════════════════════════════════════════════════════════
# Site Playbook: 03_K8s_Infra Orchestrator
# ═══════════════════════════════════════════════════════════════════════════

- import_playbook: 02_k8s_install.yml
